#!/usr/bin/env bash
set -euo pipefail

# Generate Hyprland skill reference files from the official wiki
# Source: https://github.com/hyprwm/hyprland-wiki
#
# Usage: ./scripts/generate-references.sh
#
# This script clones the wiki repo (shallow), extracts documentation pages,
# and writes them into references/ with a source header.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SKILL_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
REFS_DIR="$SKILL_DIR/references"
WIKI_REPO="https://github.com/hyprwm/hyprland-wiki.git"
WORK_DIR=$(mktemp -d)

cleanup() {
    rm -rf "$WORK_DIR"
}
trap cleanup EXIT

echo "==> Cloning hyprland-wiki (shallow)..."
git clone --depth 1 --quiet "$WIKI_REPO" "$WORK_DIR/wiki"
WIKI_DIR="$WORK_DIR/wiki/content"

# Get the latest commit info for versioning
WIKI_COMMIT=$(git -C "$WORK_DIR/wiki" rev-parse --short HEAD)
WIKI_DATE=$(git -C "$WORK_DIR/wiki" log -1 --format=%ci)

echo "==> Wiki commit: $WIKI_COMMIT ($WIKI_DATE)"

mkdir -p "$REFS_DIR"
# Remove previously generated files so renamed/dropped pages do not linger.
rm -f "$REFS_DIR"/*.md

# Pages that disappear upstream (renamed/moved) must fail the run loudly,
# otherwise reference files silently freeze at their last-copied content.
MISSING_PAGES=0

# Helper: copy a wiki page to references with a source header
# Args: source_path (relative to content/) output_filename wiki_url_path
copy_page() {
    local src="$WIKI_DIR/$1"
    local dst="$REFS_DIR/$2"
    local url_path="$3"

    if [[ ! -f "$src" ]]; then
        echo "  ERROR: $1 not found"
        MISSING_PAGES=$((MISSING_PAGES + 1))
        return
    fi

    {
        echo "<!-- source: https://wiki.hypr.land/$url_path -->"
        echo "<!-- wiki commit: $WIKI_COMMIT ($WIKI_DATE) -->"
        echo "<!-- auto-generated by scripts/generate-references.sh - DO NOT EDIT MANUALLY -->"
        echo ""
        cat "$src"
    } > "$dst"

    echo "  OK: $2"
}

# Helper: merge multiple wiki pages into one reference file
# Args: output_filename header_comment url_path source_paths...
merge_pages() {
    local name="$1"
    local dst="$REFS_DIR/$1"
    local header="$2"
    local url_path="$3"
    shift 3

    {
        echo "<!-- source: https://wiki.hypr.land/$url_path -->"
        echo "<!-- wiki commit: $WIKI_COMMIT ($WIKI_DATE) -->"
        echo "<!-- auto-generated by scripts/generate-references.sh - DO NOT EDIT MANUALLY -->"
        echo ""
        echo "# $header"
        echo ""

        for src_path in "$@"; do
            local src="$WIKI_DIR/$src_path"
            if [[ -f "$src" ]]; then
                cat "$src"
                echo ""
                echo "---"
                echo ""
            else
                echo "  ERROR: $src_path not found (merge $name)" >&2
                MISSING_PAGES=$((MISSING_PAGES + 1))
            fi
        done
    } > "$dst"

    echo "  OK: $name (merged)"
}

echo ""
echo "==> Generating reference files..."

# Wiki layout since the 2026-08-29 restructure (hyprland-wiki cba1dbc):
# lowercase paths, content/<section>/<subsection>/<page>.md.

# --- Configuring / Core ---
merge_pages "start.md" "Configuring Hyprland: Basics" "configuring/core" \
    "configuring/_index.md" \
    "configuring/core/_index.md"
copy_page "configuring/core/config-options.md"         "variables.md"             "configuring/core/config-options"
copy_page "configuring/core/dispatchers.md"            "dispatchers.md"           "configuring/core/dispatchers"
copy_page "configuring/core/autostart.md"              "autostart.md"             "configuring/core/autostart"
copy_page "configuring/core/animations.md"             "animations.md"            "configuring/core/animations"
copy_page "configuring/core/environment-variables.md"  "environment-variables.md" "configuring/core/environment-variables"
copy_page "configuring/core/devices.md"                "devices.md"               "configuring/core/devices"

merge_pages "binds.md" "Hyprland Binds Reference" "configuring/core/binds" \
    "configuring/core/binds/_index.md" \
    "configuring/core/binds/flags.md" \
    "configuring/core/binds/globals.md" \
    "configuring/core/binds/submaps.md" \
    "configuring/core/binds/switches.md" \
    "configuring/core/binds/keyboard-layouts.md" \
    "configuring/core/binds/devices/_index.md" \
    "configuring/core/binds/devices/per-device.md" \
    "configuring/core/binds/devices/mouse.md" \
    "configuring/core/binds/devices/touchpad.md"
copy_page "configuring/core/binds/gestures.md" "gestures.md" "configuring/core/binds/gestures"

merge_pages "window-rules.md" "Hyprland Window and Layer Rules Reference" "configuring/core/rules" \
    "configuring/core/rules/_index.md" \
    "configuring/core/rules/window-rules.md" \
    "configuring/core/rules/layer-rules.md"
copy_page "configuring/core/rules/workspace-rules.md" "workspace-rules.md" "configuring/core/rules/workspace-rules"

merge_pages "monitors.md" "Hyprland Monitors Reference" "configuring/core/monitors" \
    "configuring/core/monitors/_index.md" \
    "configuring/core/monitors/output-selection.md" \
    "configuring/core/monitors/modes.md" \
    "configuring/core/monitors/positioning.md" \
    "configuring/core/monitors/colors.md"

# Advanced configuration (Lua scripting)
merge_pages "lua-scripting.md" "Hyprland Lua Scripting: Events and Utilities" "configuring/core/advanced-configuration" \
    "configuring/core/advanced-configuration/_index.md" \
    "configuring/core/advanced-configuration/events.md" \
    "configuring/core/advanced-configuration/lua-utilities.md"
copy_page "configuring/core/advanced-configuration/using-hyprctl.md" "hyprctl.md"       "configuring/core/advanced-configuration/using-hyprctl"
copy_page "configuring/core/advanced-configuration/notifications.md" "notifications.md" "configuring/core/advanced-configuration/notifications"
copy_page "configuring/core/advanced-configuration/permissions.md"   "permissions.md"   "configuring/core/advanced-configuration/permissions"

# --- Configuring / Extra ---
copy_page "configuring/extra/performance.md" "performance.md" "configuring/extra/performance"
copy_page "configuring/extra/xwayland.md"    "xwayland.md"    "configuring/extra/xwayland"
copy_page "configuring/extra/tearing.md"     "tearing.md"     "configuring/extra/tearing"
copy_page "configuring/extra/multi-gpu.md"   "multi-gpu.md"   "configuring/extra/multi-gpu"
copy_page "configuring/extra/virtual-gpu.md" "virtual-gpu.md" "configuring/extra/virtual-gpu"
copy_page "configuring/extra/systemd.md"     "systemd.md"     "configuring/extra/systemd"

# --- Configuring / misc ---
copy_page "configuring/code-snippets.md"       "code-snippets.md"       "configuring/code-snippets"
copy_page "configuring/naming-conventions.md"  "naming-conventions.md"  "configuring/naming-conventions"

# --- Layouts ---
merge_pages "layouts.md" "Hyprland Layouts Reference" "configuring/layouts" \
    "configuring/layouts/dwindle-layout.md" \
    "configuring/layouts/master-layout.md" \
    "configuring/layouts/scrolling-layout.md" \
    "configuring/layouts/monocle-layout.md" \
    "configuring/layouts/custom-layouts.md"

# --- IPC ---
copy_page "ipc/_index.md" "ipc.md" "ipc"

# --- Plugins ---
merge_pages "plugins.md" "Hyprland Plugins Reference" "hyprland-plugins" \
    "hyprland-plugins/using-plugins.md" \
    "hyprland-plugins/development/_index.md" \
    "hyprland-plugins/development/getting-started.md" \
    "hyprland-plugins/development/advanced.md" \
    "hyprland-plugins/development/plugin-guidelines.md"

# --- Nix ---
merge_pages "nix.md" "Hyprland on NixOS / Nix Reference" "nix" \
    "nix/_index.md" \
    "nix/installing-hyprland-on-nixos.md" \
    "nix/configuring-hyprland-with-home-manager.md" \
    "nix/configuring-hyprland-with-hjem.md" \
    "nix/hyprland-on-any-distro-using-nix.md" \
    "nix/cachix.md" \
    "nix/advanced.md" \
    "nix/contributing-and-debugging.md"

# --- Nvidia ---
copy_page "nvidia/_index.md" "nvidia.md" "nvidia"

# --- FAQ ---
copy_page "faq/_index.md" "faq.md" "faq"

# --- Getting Started ---
merge_pages "getting-started.md" "Getting Started with Hyprland" "getting-started" \
    "getting-started/_index.md" \
    "getting-started/installation.md" \
    "getting-started/master-tutorial.md" \
    "getting-started/preconfigured-setups.md"

# --- Hypr Ecosystem: user apps ---
copy_page "hypr-ecosystem/user/hyprlock.md"                   "hyprlock.md"            "hypr-ecosystem/user/hyprlock"
copy_page "hypr-ecosystem/user/hypridle.md"                   "hypridle.md"            "hypr-ecosystem/user/hypridle"
copy_page "hypr-ecosystem/user/hyprpaper.md"                  "hyprpaper.md"           "hypr-ecosystem/user/hyprpaper"
copy_page "hypr-ecosystem/user/hyprlauncher.md"               "hyprlauncher.md"        "hypr-ecosystem/user/hyprlauncher"
copy_page "hypr-ecosystem/user/hyprpicker.md"                 "hyprpicker.md"          "hypr-ecosystem/user/hyprpicker"
copy_page "hypr-ecosystem/user/hyprsunset.md"                 "hyprsunset.md"          "hypr-ecosystem/user/hyprsunset"
copy_page "hypr-ecosystem/user/xdg-desktop-portal-hyprland.md" "xdph.md"              "hypr-ecosystem/user/xdg-desktop-portal-hyprland"
copy_page "hypr-ecosystem/user/hyprcursor.md"                 "hyprcursor.md"          "hypr-ecosystem/user/hyprcursor"
copy_page "hypr-ecosystem/user/hyprpwcenter.md"               "hyprpwcenter.md"        "hypr-ecosystem/user/hyprpwcenter"
copy_page "hypr-ecosystem/user/hyprsysteminfo.md"             "hyprsysteminfo.md"      "hypr-ecosystem/user/hyprsysteminfo"
copy_page "hypr-ecosystem/user/hyprpolkitagent.md"            "hyprpolkitagent.md"     "hypr-ecosystem/user/hyprpolkitagent"
copy_page "hypr-ecosystem/user/hyprshutdown.md"               "hyprshutdown.md"        "hypr-ecosystem/user/hyprshutdown"
merge_pages "hyprland-qt-support.md" "Hyprland Qt Support" "hypr-ecosystem/user/hyprland-qt-support" \
    "hypr-ecosystem/user/hyprland-qt-support.md" \
    "hypr-ecosystem/user/hyprqt6engine.md"

# --- Hypr Ecosystem: developer libraries ---
merge_pages "hypr-libraries.md" "Hypr Ecosystem Libraries Reference" "hypr-ecosystem" \
    "hypr-ecosystem/_index.md" \
    "hypr-ecosystem/user/hyprtoolkit.md" \
    "hypr-ecosystem/dev/hyprtoolkit.md" \
    "hypr-ecosystem/dev/hyprlang.md" \
    "hypr-ecosystem/dev/hyprutils.md" \
    "hypr-ecosystem/dev/hyprgraphics.md" \
    "hypr-ecosystem/dev/aquamarine.md" \
    "hypr-ecosystem/dev/hyprwayland-scanner.md" \
    "hypr-ecosystem/dev/hyprland-guiutils.md"

# --- Useful Utilities ---
merge_pages "useful-utilities.md" "Useful Utilities for Hyprland" "useful-utilities" \
    "useful-utilities/must-have.md" \
    "useful-utilities/uwsm.md" \
    "useful-utilities/status-bars.md" \
    "useful-utilities/app-launchers.md" \
    "useful-utilities/app-clients.md" \
    "useful-utilities/wallpapers.md" \
    "useful-utilities/screen-sharing.md" \
    "useful-utilities/screenshots-and-recording.md" \
    "useful-utilities/clipboard-managers.md" \
    "useful-utilities/color-pickers.md" \
    "useful-utilities/file-managers.md" \
    "useful-utilities/phone-connect.md" \
    "useful-utilities/hypr-ecosystem.md" \
    "useful-utilities/other.md"

# --- Contributing ---
merge_pages "contributing.md" "Contributing and Debugging" "contributing-and-debugging" \
    "contributing-and-debugging/_index.md" \
    "contributing-and-debugging/issue-guidelines.md" \
    "contributing-and-debugging/pr-guidelines.md" \
    "contributing-and-debugging/wiki-guidelines.md" \
    "contributing-and-debugging/tests.md" \
    "contributing-and-debugging/translations.md"

# --- Crashes ---
copy_page "crashes-and-bugs/_index.md" "crashes-and-bugs.md" "crashes-and-bugs"

if [[ $MISSING_PAGES -gt 0 ]]; then
    echo ""
    echo "==> ERROR: $MISSING_PAGES expected wiki page(s) missing." >&2
    echo "    The wiki was likely reorganized upstream. Update the page list" >&2
    echo "    in this script, otherwise reference files silently go stale." >&2
    exit 1
fi

echo ""
echo "==> Writing metadata..."

# Write version info
cat > "$REFS_DIR/.wiki-version" <<EOF
commit='$WIKI_COMMIT'
date='$WIKI_DATE'
EOF

# Count results
TOTAL=$(find "$REFS_DIR" -name '*.md' | wc -l)
echo "==> Done! Generated $TOTAL reference files from wiki commit $WIKI_COMMIT"
echo "    Output: $REFS_DIR/"
