#!/usr/bin/env bash
set -euo pipefail

# Generate Hyprland skill reference files from the official wiki
# Source: https://github.com/hyprwm/hyprland-wiki
#
# Usage: ./scripts/generate-references.sh
#
# This script clones the wiki repo (shallow), extracts documentation pages,
# and writes them into references/ with a source header.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SKILL_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
REFS_DIR="$SKILL_DIR/references"
WIKI_REPO="https://github.com/hyprwm/hyprland-wiki.git"
WORK_DIR=$(mktemp -d)

cleanup() {
    rm -rf "$WORK_DIR"
}
trap cleanup EXIT

echo "==> Cloning hyprland-wiki (shallow)..."
git clone --depth 1 --quiet "$WIKI_REPO" "$WORK_DIR/wiki"
WIKI_DIR="$WORK_DIR/wiki/content"

# Get the latest commit info for versioning
WIKI_COMMIT=$(git -C "$WORK_DIR/wiki" rev-parse --short HEAD)
WIKI_DATE=$(git -C "$WORK_DIR/wiki" log -1 --format=%ci)

echo "==> Wiki commit: $WIKI_COMMIT ($WIKI_DATE)"

mkdir -p "$REFS_DIR"

# Pages that disappear upstream (renamed/moved) must fail the run loudly,
# otherwise reference files silently freeze at their last-copied content.
MISSING_PAGES=0

# Helper: copy a wiki page to references with a source header
# Args: source_path (relative to content/) output_filename wiki_url_path
copy_page() {
    local src="$WIKI_DIR/$1"
    local dst="$REFS_DIR/$2"
    local url_path="$3"

    if [[ ! -f "$src" ]]; then
        echo "  ERROR: $1 not found"
        MISSING_PAGES=$((MISSING_PAGES + 1))
        return
    fi

    {
        echo "<!-- source: https://wiki.hypr.land/$url_path -->"
        echo "<!-- wiki commit: $WIKI_COMMIT ($WIKI_DATE) -->"
        echo "<!-- auto-generated by scripts/generate-references.sh - DO NOT EDIT MANUALLY -->"
        echo ""
        cat "$src"
    } > "$dst"

    echo "  OK: $2"
}

# Helper: merge multiple wiki pages into one reference file
# Args: output_filename header_comment url_path source_paths...
merge_pages() {
    local name="$1"
    local dst="$REFS_DIR/$1"
    local header="$2"
    local url_path="$3"
    shift 3

    {
        echo "<!-- source: https://wiki.hypr.land/$url_path -->"
        echo "<!-- wiki commit: $WIKI_COMMIT ($WIKI_DATE) -->"
        echo "<!-- auto-generated by scripts/generate-references.sh - DO NOT EDIT MANUALLY -->"
        echo ""
        echo "# $header"
        echo ""

        for src_path in "$@"; do
            local src="$WIKI_DIR/$src_path"
            if [[ -f "$src" ]]; then
                cat "$src"
                echo ""
                echo "---"
                echo ""
            else
                echo "  ERROR: $src_path not found (merge $name)" >&2
                MISSING_PAGES=$((MISSING_PAGES + 1))
            fi
        done
    } > "$dst"

    echo "  OK: $name (merged)"
}

echo ""
echo "==> Generating reference files..."

# --- Configuring ---
copy_page "Configuring/Start.md"                  "start.md"                  "Configuring/Start"
copy_page "Configuring/Example-configurations.md" "example-configurations.md" "Configuring/Example-configurations"

# Basics
copy_page "Configuring/Basics/Variables.md"       "variables.md"       "Configuring/Basics/Variables"
copy_page "Configuring/Basics/Binds.md"           "binds.md"           "Configuring/Basics/Binds"
copy_page "Configuring/Basics/Dispatchers.md"     "dispatchers.md"     "Configuring/Basics/Dispatchers"
copy_page "Configuring/Basics/Window-Rules.md"    "window-rules.md"    "Configuring/Basics/Window-Rules"
copy_page "Configuring/Basics/Monitors.md"        "monitors.md"        "Configuring/Basics/Monitors"
copy_page "Configuring/Basics/Workspace-Rules.md" "workspace-rules.md" "Configuring/Basics/Workspace-Rules"
copy_page "Configuring/Basics/Autostart.md"       "autostart.md"       "Configuring/Basics/Autostart"

# Advanced and Cool
copy_page "Configuring/Advanced and Cool/Animations.md"              "animations.md"              "Configuring/Advanced-and-Cool/Animations"
copy_page "Configuring/Advanced and Cool/Using-hyprctl.md"           "hyprctl.md"                 "Configuring/Advanced-and-Cool/Using-hyprctl"
copy_page "Configuring/Advanced and Cool/Environment-variables.md"   "environment-variables.md"   "Configuring/Advanced-and-Cool/Environment-variables"
copy_page "Configuring/Advanced and Cool/Performance.md"             "performance.md"             "Configuring/Advanced-and-Cool/Performance"
copy_page "Configuring/Advanced and Cool/XWayland.md"                "xwayland.md"                "Configuring/Advanced-and-Cool/XWayland"
copy_page "Configuring/Advanced and Cool/Tearing.md"                 "tearing.md"                 "Configuring/Advanced-and-Cool/Tearing"
copy_page "Configuring/Advanced and Cool/Multi-GPU.md"               "multi-gpu.md"               "Configuring/Advanced-and-Cool/Multi-GPU"
copy_page "Configuring/Advanced and Cool/Permissions.md"             "permissions.md"             "Configuring/Advanced-and-Cool/Permissions"
copy_page "Configuring/Advanced and Cool/Gestures.md"                "gestures.md"                "Configuring/Advanced-and-Cool/Gestures"
copy_page "Configuring/Advanced and Cool/Devices.md"                 "devices.md"                 "Configuring/Advanced-and-Cool/Devices"
copy_page "Configuring/Advanced and Cool/Expanding-functionality.md" "expanding-functionality.md" "Configuring/Advanced-and-Cool/Expanding-functionality"
copy_page "Configuring/Advanced and Cool/Notifications.md"           "notifications.md"           "Configuring/Advanced-and-Cool/Notifications"
copy_page "Configuring/Advanced and Cool/Uncommon-tips-and-tricks.md" "uncommon-tips-and-tricks.md" "Configuring/Advanced-and-Cool/Uncommon-tips-and-tricks"
copy_page "Configuring/Advanced and Cool/Virtual-GPU.md"             "virtual-gpu.md"             "Configuring/Advanced-and-Cool/Virtual-GPU"

# Layouts: merge all layout pages into one
merge_pages "layouts.md" "Hyprland Layouts Reference" "Configuring/Layouts" \
    "Configuring/Layouts/Dwindle-Layout.md" \
    "Configuring/Layouts/Master-Layout.md" \
    "Configuring/Layouts/Scrolling-Layout.md" \
    "Configuring/Layouts/Monocle-Layout.md" \
    "Configuring/Layouts/Custom-Layouts.md"

# --- IPC ---
copy_page "IPC/_index.md" "ipc.md" "IPC"

# --- Plugins ---
merge_pages "plugins.md" "Hyprland Plugins Reference" "Plugins/Using-Plugins" \
    "Plugins/Using-Plugins.md" \
    "Plugins/Development/Getting-Started.md" \
    "Plugins/Development/Advanced.md" \
    "Plugins/Development/Plugin-Guidelines.md"

# --- Nix ---
merge_pages "nix.md" "Hyprland on NixOS / Nix Reference" "Nix/Hyprland-on-NixOS" \
    "Nix/Hyprland on NixOS.md" \
    "Nix/Hyprland on Home Manager.md" \
    "Nix/Hyprland on other distros.md" \
    "Nix/Cachix.md" \
    "Nix/Options & Overrides.md" \
    "Nix/Plugins.md" \
    "Nix/Contributing and Debugging.md"

# --- Nvidia ---
copy_page "Nvidia/_index.md" "nvidia.md" "Nvidia"

# --- FAQ ---
copy_page "FAQ/_index.md" "faq.md" "FAQ"

# --- Getting Started ---
merge_pages "getting-started.md" "Getting Started with Hyprland" "Getting-Started/Installation" \
    "Getting Started/Installation.md" \
    "Getting Started/Master-Tutorial.md" \
    "Getting Started/Preconfigured-setups.md"

# --- Hypr Ecosystem ---
copy_page "Hypr Ecosystem/hyprlock.md"                      "hyprlock.md"    "Hypr-Ecosystem/hyprlock"
copy_page "Hypr Ecosystem/hypridle.md"                       "hypridle.md"    "Hypr-Ecosystem/hypridle"
copy_page "Hypr Ecosystem/hyprpaper.md"                      "hyprpaper.md"   "Hypr-Ecosystem/hyprpaper"
copy_page "Hypr Ecosystem/hyprlauncher.md"                   "hyprlauncher.md" "Hypr-Ecosystem/hyprlauncher"
copy_page "Hypr Ecosystem/hyprpicker.md"                     "hyprpicker.md"  "Hypr-Ecosystem/hyprpicker"
copy_page "Hypr Ecosystem/hyprsunset.md"                     "hyprsunset.md"  "Hypr-Ecosystem/hyprsunset"
copy_page "Hypr Ecosystem/xdg-desktop-portal-hyprland.md"    "xdph.md"       "Hypr-Ecosystem/xdg-desktop-portal-hyprland"
copy_page "Hypr Ecosystem/hyprcursor.md"                     "hyprcursor.md"  "Hypr-Ecosystem/hyprcursor"
copy_page "Hypr Ecosystem/hyprpwcenter.md"                   "hyprpwcenter.md" "Hypr-Ecosystem/hyprpwcenter"
copy_page "Hypr Ecosystem/hyprsysteminfo.md"                 "hyprsysteminfo.md" "Hypr-Ecosystem/hyprsysteminfo"
copy_page "Hypr Ecosystem/hyprpolkitagent.md"                "hyprpolkitagent.md" "Hypr-Ecosystem/hyprpolkitagent"
copy_page "Hypr Ecosystem/hyprshutdown.md"                   "hyprshutdown.md" "Hypr-Ecosystem/hyprshutdown"
copy_page "Hypr Ecosystem/hyprland-qt-support.md"            "hyprland-qt-support.md" "Hypr-Ecosystem/hyprland-qt-support"

# Developer-facing Hypr libraries: merge into one reference
merge_pages "hypr-libraries.md" "Hypr Ecosystem Libraries Reference" "Hypr-Ecosystem" \
    "Hypr Ecosystem/hyprtoolkit/_index.md" \
    "Hypr Ecosystem/hyprtoolkit/development.md" \
    "Hypr Ecosystem/hyprlang.md" \
    "Hypr Ecosystem/hyprutils.md" \
    "Hypr Ecosystem/hyprgraphics.md" \
    "Hypr Ecosystem/aquamarine.md" \
    "Hypr Ecosystem/hyprwayland-scanner.md" \
    "Hypr Ecosystem/hyprland-guiutils.md" \
    "Hypr Ecosystem/hyprqt6engine.md"

# --- Useful Utilities ---
merge_pages "useful-utilities.md" "Useful Utilities for Hyprland" "Useful-Utilities/Must-have" \
    "Useful Utilities/Must-have.md" \
    "Useful Utilities/Status-Bars.md" \
    "Useful Utilities/App-Launchers.md" \
    "Useful Utilities/App-Clients.md" \
    "Useful Utilities/Wallpapers.md" \
    "Useful Utilities/Screen-Sharing.md" \
    "Useful Utilities/Screenshots-and-Recording.md" \
    "Useful Utilities/Clipboard-Managers.md" \
    "Useful Utilities/Color-Pickers.md" \
    "Useful Utilities/File-Managers.md" \
    "Useful Utilities/Phone-connect.md" \
    "Useful Utilities/Systemd-start.md" \
    "Useful Utilities/Hypr-Ecosystem.md" \
    "Useful Utilities/Other.md"

# --- Contributing ---
merge_pages "contributing.md" "Contributing and Debugging" "Contributing-and-Debugging" \
    "Contributing and Debugging/_index.md" \
    "Contributing and Debugging/Issue-Guidelines.md" \
    "Contributing and Debugging/PR-Guidelines.md" \
    "Contributing and Debugging/Tests.md" \
    "Contributing and Debugging/Translations.md"

# --- Crashes ---
copy_page "Crashes and Bugs/_index.md" "crashes-and-bugs.md" "Crashes-and-Bugs"

if [[ $MISSING_PAGES -gt 0 ]]; then
    echo ""
    echo "==> ERROR: $MISSING_PAGES expected wiki page(s) missing." >&2
    echo "    The wiki was likely reorganized upstream. Update the page list" >&2
    echo "    in this script, otherwise reference files silently go stale." >&2
    exit 1
fi

echo ""
echo "==> Writing metadata..."

# Write version info
cat > "$REFS_DIR/.wiki-version" <<EOF
commit='$WIKI_COMMIT'
date='$WIKI_DATE'
EOF

# Count results
TOTAL=$(find "$REFS_DIR" -name '*.md' | wc -l)
echo "==> Done! Generated $TOTAL reference files from wiki commit $WIKI_COMMIT"
echo "    Output: $REFS_DIR/"
